default: &default
  adapter: postgresql
  encoding: unicode
  database: codejudge
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: codejudge_dev

test:
  <<: *default
  database: codejudge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
